[tool.pycodestyle]
max-line-length = 100

[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = false
warn_return_any = false
warn_unused_ignores = true
check_untyped_defs = false
explicit_package_bases = true
